QueryAPI
kentik/community_sdk_golang pull request #11
Opened 2021-02-26 07:44 UTC by mateuszmidor

KNTK-166

2021-03-09 18:21 UTC, Fenthick requested changes

2021-03-10 13:09 UTC, mateuszmidor commented on kentikapi/internal/api_endpoints/query.go
> +func QueryURL() string {
QueryURL is the name of the endpoint, so in the code using it reads as:
api_endpoints.QueryURL()
I can use const strings but decided to keep this consistent with other resources in api_endpoints package.

2021-03-10 13:12 UTC, mateuszmidor commented on kentikapi/internal/api_payloads/query_test.go
> +func TestQueryChartResponsePNGToQueryChartResult(t *testing.T) {
We can run a polish-up phase in a spare moment, this test works so let's keep it as it is for now.

2021-03-10 16:50 UTC, Fenthick commented on examples/query_example_test.go
> +	filename := "/tmp/chart.png"
Done

2021-03-10 16:51 UTC, Fenthick commented on kentikapi/internal/api_endpoints/query.go
> +// QuerySQL runs SQL command against all configured devices. Returns top X datasets.
Done

2021-03-10 16:52 UTC, Fenthick commented on kentikapi/internal/api_payloads/query_test.go
> +func TestQueryChartResponsePNGToQueryChartResult(t *testing.T) {
Ok

2021-03-10 16:54 UTC, Fenthick approved these changes

2021-03-12 16:58 UTC, TedatKentik approved these changes
Query API

2021-03-12 16:58 UTC, merged