CustomApplicationsAPI
kentik/community_sdk_golang pull request #12
Opened 2021-02-26 13:42 UTC by mateuszmidor

KNTK-174.
Note: Filters will be added once SavedFiltersAPI is ready.

2021-03-10 11:21 UTC, Fenthick requested changes

2021-03-10 11:21 UTC, Fenthick commented on kentikapi/internal/api_resources/custom_applications_test.go
> +	assert.Zero(transport.RequestBody)
Please verify the request path in all tests.

2021-03-11 16:41 UTC, Fenthick commented on kentikapi/internal/api_resources/custom_applications_test.go
> +	assert.Zero(transport.RequestBody)
Resolved

2021-03-11 16:41 UTC, Fenthick approved these changes

2021-03-15 11:11 UTC, lukaa12 submitted a review, later dismissed

2021-03-15 12:27 UTC, Fenthick approved these changes

2021-03-15 17:53 UTC, TedatKentik approved these changes
Implement custom applications

2021-03-15 17:53 UTC, merged