CustomDimensionsAPI
kentik/community_sdk_golang pull request #13
Opened 2021-03-01 12:28 UTC by mateuszmidor

KNTK-173

2021-03-10 12:52 UTC, Fenthick requested changes

2021-03-10 12:52 UTC, Fenthick commented on kentikapi/internal/api_resources/custom_dimensions_test.go
> +	require.NoError(err)
Please verify the request path in all tests

2021-03-15 11:53 UTC, lukaa12 approved these changes

2021-03-17 09:55 UTC, Fenthick commented on kentikapi/internal/api_resources/custom_dimensions_test.go
> +	require.NoError(err)
Done

2021-03-17 09:55 UTC, Fenthick approved these changes

2021-03-17 13:20 UTC, TedatKentik approved these changes

2021-03-17 13:20 UTC, merged