DevicesAPI: Interfaces: Create, Update, Delete
kentik/community_sdk_golang pull request #6
Opened 2021-02-22 14:27 UTC by mateuszmidor

KNTK-167

2021-02-23 17:36 UTC, Fenthick requested changes
Good job!

2021-02-23 17:36 UTC, Fenthick commented on kentikapi/internal/api_resources/devices.go
> +	if err := a.DeleteAndValidate(ctx, api_endpoints.DeleteInterface(deviceID, interfaceID), nil); err != nil {
```suggestion
	return a.DeleteAndValidate(ctx, api_endpoints.DeleteInterface(deviceID, interfaceID), nil)
```

2021-02-23 17:36 UTC, Fenthick commented on kentikapi/models/interface.go
> +// Note: InterfacesAPI belong under DevicesAPI but it is wast so it lives in a separate file
```suggestion
// Note: InterfacesAPI belongs under DevicesAPI but it is vast so it lives in a separate file
```

2021-02-24 07:35 UTC, mateuszmidor commented on examples/devices_example_test.go
> +	PanicOnError(err)
Alright, just bear in mind this will ruin the readability of the examples

2021-02-24 07:42 UTC, mateuszmidor commented on kentikapi/internal/api_payloads/interface.go
> +	err := utils.ConvertOrNone(i.VRF, vrfAttributesToPayload, &vrf)
It seems this gains us -2 lines of code :)

2021-02-24 07:47 UTC, mateuszmidor commented on kentikapi/internal/api_payloads/interface.go
> +	err = utils.ConvertList(i.SecondaryIPS, secondaryIPToPayload, &secondaryIPs)
again, this change is of little profit, just moves the code around.

2021-02-24 07:50 UTC, mateuszmidor commented on kentikapi/internal/api_payloads/broken_int.go
> +type BrokenInt int
IntAsString will do

2021-02-24 09:49 UTC, Fenthick commented on examples/devices_example_test.go
> +	PanicOnError(err)
Come on, this is just ordinary Go code. Some say it is readable ;)

2021-02-24 09:51 UTC, Fenthick commented on kentikapi/internal/api_payloads/broken_int.go
> +type BrokenInt int
Done

2021-02-24 10:16 UTC, Fenthick commented on kentikapi/internal/api_payloads/interface.go
> +	err := utils.ConvertOrNone(i.VRF, vrfAttributesToPayload, &vrf)
This is not about number of LoC.
1. Using ConvertOrNone introduces return error value, which increases complexity (error bubbles up the function stack).
2. Input and output parameters of ConvertOrNone function are `interface{}`, so there is no type safety, the implementation might have bugs that are discovered in run-time. Also, this API is harder to read, use and modify.
3. Implementation of ConvertOrNone that uses interface{} and reflections is probably less performant (which will probably never be an issue, tough)

The same arguments apply to ConvertList below.

2021-02-24 10:17 UTC, Fenthick commented on kentikapi/internal/api_payloads/interface.go
> +	err = utils.ConvertList(i.SecondaryIPS, secondaryIPToPayload, &secondaryIPs)
Responded here: https://github.com/kentik/community_sdk_golang/pull/6#discussion_r581831715

2021-02-24 10:19 UTC, Fenthick approved these changes
I added more info about conversion functions. Please take a look and revisit your decision. 
I won't block the PR

2021-02-24 13:46 UTC, mateuszmidor commented on kentikapi/internal/api_payloads/interface.go
> +	err := utils.ConvertOrNone(i.VRF, vrfAttributesToPayload, &vrf)
Alright, we can park this for refactor when the schedule is less tight

2021-02-24 14:44 UTC, lukaa12 approved these changes

2021-02-24 15:55 UTC, TedatKentik approved these changes
Devices API, GetAll, create update delete

2021-02-24 15:55 UTC, merged