Remove HTTP part of the client for API v6 services
kentik/community_sdk_golang pull request #70
Opened 2021-12-14 13:05 UTC by Opelord

Issue: KNTK 370
Firstly this PR clears repo of depracated HTTP services for API v6.
In addition some improvements can be found for timeout tests and gRPC examples in separate commits.

2021-12-15 10:33 UTC, mateuszmidor commented
While running the users example, I get back an error:
`go test -tags examples -count 1 -v -run Users github.com/kentik/community_sdk_golang/examples`
```
go: finding module for package github.com/kentik/community_sdk_golang/kentikapi/synthetics
# github.com/kentik/community_sdk_golang/examples
examples/synthetics_example_test.go:14:2: no matching versions for query "latest"
FAIL    github.com/kentik/community_sdk_golang/examples [setup failed]
FAIL
```
It works fine on master.

2021-12-15 11:34 UTC, mateuszmidor commented on examples/synthetics_example_test.go
> +func runGRPCGetHealthForTests(ctx context.Context, client *kentikapi.Client, testID string) error {
No longer GetHealthForTests, just single Test now

2021-12-15 11:53 UTC, mateuszmidor commented on examples/synthetics_mesh_example_test.go
> +	return "", fmt.Errorf("No tests with type application_mesh: %v", err)
I would include information that there is no such tests but specifically for requested Kentik Account 
err here is most likely always nil?

2021-12-15 12:39 UTC, mateuszmidor requested changes
There is an issue with running examples the way README suggests

2021-12-16 08:42 UTC, mateuszmidor approved these changes

2021-12-21 06:17 UTC, mmac-m3a approved these changes

2021-12-21 06:17 UTC, merged

2021-12-22 15:37 UTC, Fenthick commented on examples/synthetics_mesh_example_test.go
> +	mesh, err := getMeshTestResultsGRPC(testID)
-> `getMeshTestResults`
There is no need for gRPC suffix. In other places in examples/tests too.