Configured CI to build all packages
kentik/community_sdk_golang pull request #75
Opened 2021-12-30 15:25 UTC by Opelord

Issues: KNTK-368

2021-12-31 12:18 UTC, Fenthick requested changes

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +  build:
Please move it above _test_ job and run tests only when build succeeds.

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +    name: Build binary
```suggestion
    name: Build code
```
We're building multible non-executable binary object files here so name _binary_ doesn't sound right for me.

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +    runs-on: 'ubuntu-latest'
```suggestion
    runs-on: ubuntu-latest
```
FYI there is no need for `'` nor `"` for YAML strings

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +          - 'linux/386'
As discussed, please use linux/amd64, windows/amd64, darwin/amd64, darwin/arm

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +          - 1.16.x
As discussed, please bump go versions up to 1.17

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +      - uses: actions/setup-go@v2
Nit: please name it `- name: Install Go`

2021-12-31 12:18 UTC, Fenthick commented on .github/workflows/test.yml
> +          go build -tags examples ./...
As discussed, this command compiler all code and is sufficent by itself

2022-01-04 12:07 UTC, mateuszmidor approved these changes

2022-01-11 15:58 UTC, Fenthick commented on .github/workflows/test.yml
> +  build:
Done

2022-01-11 15:58 UTC, Fenthick commented on .github/workflows/test.yml
> +    name: Build binary
Done

2022-01-11 15:58 UTC, Fenthick commented on .github/workflows/test.yml
> +    runs-on: 'ubuntu-latest'
Done

2022-01-11 15:59 UTC, Fenthick commented on .github/workflows/test.yml
> +          - 'linux/386'
Done

2022-01-11 15:59 UTC, Fenthick commented on .github/workflows/test.yml
> +          - 1.16.x
Done

2022-01-11 16:01 UTC, Fenthick commented on .github/workflows/test.yml
> +      - uses: actions/setup-go@v2
Done

2022-01-11 16:01 UTC, Fenthick commented on .github/workflows/test.yml
> +          go build -tags examples ./...
Done

2022-01-11 16:04 UTC, Fenthick approved these changes

2022-01-13 03:33 UTC, mmac-m3a reviewed
I'll hold on reviewing this until previous PRs are merged and this change rebased, so I don't have to go over the same files again.

2022-01-15 02:24 UTC, mmac-m3a approved these changes

2022-01-15 02:24 UTC, merged