RequiredFields structs for constructors of models
kentik/community_sdk_golang pull request #82
Opened 2022-03-01 15:10 UTC by jdziurzynski

KNTK - 381

Refactored constructors of models to take struct with required fields. 
Example https://github.com/kentik/community_sdk_golang/blob/62e10d7f63f093e5af9d9911a99f1fd48abc1395/kentikapi/models/user.go#L26

Also added `Count` to makeExampleTest() in examples/synthetics_example_test.go as it became required.

2022-03-16 16:09 UTC, danielfurman requested changes

2022-03-16 16:09 UTC, danielfurman commented on examples/custom_dimensions_example_test.go
Please create and use missing constructors:
- NewManualMitigation()
- NewSavedFilter()

2022-03-17 13:04 UTC, mateuszmidor approved these changes
Looks neat!

2022-03-22 08:51 UTC, danielfurman commented on examples/custom_dimensions_example_test.go
Done

2022-03-22 08:51 UTC, danielfurman approved these changes

2022-03-22 18:11 UTC, mmac-m3a approved these changes

2022-03-22 18:11 UTC, merged