CE create & update requests validation added
kentik/community_sdk_golang pull request #98
Opened 2022-04-25 11:50 UTC by jdziurzynski

KNTK-401

Implemented validation for create and update CloudExport API requests.

2022-04-25 12:27 UTC, mateuszmidor approved these changes

2022-04-27 09:58 UTC, danielfurman requested changes

2022-04-27 09:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +//nolint:gocyclo
Please extract validateCEProperties function to increase readability. Unless you think that the cyclomatic complexity threshold is too low.

2022-04-27 09:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +		return nil
```suggestion
		return fmt.Errorf("cloud export object is nil")
```
This should be an error, because there is no point in sending empty requests. Please also modify "nil request" subtest, of course.

2022-04-27 09:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +
Please do not mix-up resource-agnostic validation helpers with resource-specific validation code. I suggest to move cloud export validation to cloud_export.go file.

2022-04-27 09:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +		return nil
```suggestion
		return fmt.Errorf("cloud export object is nil")
```

2022-04-27 09:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +func ValidateCEUpdateRequest(ce *models.CloudExport) error {
Is update request with missing fields that are required for create (e.g. Name, PlanID, Properties.Bucket) accepted by the Kentik API?

2022-04-29 09:36 UTC, jdziurzynski commented on kentikapi/internal/validation/validate.go
> +func ValidateCEUpdateRequest(ce *models.CloudExport) error {
You're right. I added the missing validation.

2022-04-30 00:46 UTC, mmac-m3a approved these changes
LGTM

2022-04-30 00:48 UTC, mmac-m3a commented
You need to fix the failing test, before the code can be merged.

2022-05-06 11:17 UTC, danielfurman requested changes

2022-05-06 11:17 UTC, danielfurman commented on kentikapi/cloud_exports_integration_test.go
> +			if tt.request != nil && assert.Equal(t, 1, len(server.requests.createCERequests), "invalid number of requests") {
```suggestion
			if tt.expectedRequest != nil && assert.Equal(t, 1, len(server.requests.createCERequests), "invalid number of requests") {
```
Little more readable. If there is no expected request, do not verify it.
Also, the name of the test "nil request, status InvalidArgument received" should be changed to e.g. "nil request", because no request is performed in that case. Also, `tt.response` should be removed there, because it is not needed and we want to keep code lean.

2022-05-06 11:17 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		if ce.GetAWSProperties().Bucket == "" {
```suggestion
                if ce.GetAWSProperties() == nil {return ceFieldError("Properties") }
		if ce.GetAWSProperties().Bucket == "" {
```
GetAWSProperties() might return nil pointer and nil pointer dereference causes panic. We need to do nil check to avoid that.

2022-05-06 11:17 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +func ValidateCECreateRequest(ce *models.CloudExport) error {
Please add a test for create request validation and update request validation. It might be a subtest in integration tests, that we already have. I suggest to test a missing AWS.Bucket field both for update and create. I know that testing every missing field is an overkill, but we should verify that the code works.

2022-05-06 11:18 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +//nolint:gocyclo
I still see `nolint` statement in the code, so the comment is still valid. Please extract more functions or let's discuss increasing gocyclo thershold.

2022-05-06 11:19 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +		return nil
Done. Added separate comment for "nil request" subtest

2022-05-06 11:19 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +
Done. Moving validation code to api_payloads package is acceptable for me, altough my comment didn't suggest that.

2022-05-06 11:20 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +		return nil
Done

2022-05-06 11:20 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +func ValidateCEUpdateRequest(ce *models.CloudExport) error {
Done

2022-05-17 11:55 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		if err := validateAWSProvider(ce); err != nil {
```suggestion
		return validateAWSProvider(ce)
```
Minor simplification

2022-05-17 11:55 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		return fmt.Errorf("CloudExport provider '%s' is not supported", ce.CloudProvider)
```suggestion
		return fmt.Errorf("cloud provider '%s' is not supported", ce.CloudProvider)
```

2022-05-17 11:55 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		if ce.GetAWSProperties().Bucket == "" {
This comment also applies to other providers, e.g. Azure

2022-05-17 11:58 UTC, danielfurman commented on kentikapi/internal/validation/validate.go
> +//nolint:gocyclo
Done

2022-05-17 12:00 UTC, danielfurman commented on kentikapi/cloud_exports_integration_test.go
> +			if tt.request != nil && assert.Equal(t, 1, len(server.requests.createCERequests), "invalid number of requests") {
Done

2022-05-17 12:01 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +func ValidateCECreateRequest(ce *models.CloudExport) error {
Done

2022-05-17 12:01 UTC, danielfurman requested changes
As soon as we remove possible panics from functions validating properties it's good to go

2022-05-20 08:16 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		if ce.GetAWSProperties().Bucket == "" {
Done

2022-05-20 08:16 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		if err := validateAWSProvider(ce); err != nil {
Done

2022-05-20 08:17 UTC, danielfurman commented on kentikapi/internal/api_payloads/cloud_export.go
> +		return fmt.Errorf("CloudExport provider '%s' is not supported", ce.CloudProvider)
Done

2022-05-20 08:17 UTC, danielfurman approved these changes
Nice

2022-05-21 01:30 UTC, merged